version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - sudo apt-get -y install wget
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - cd /usr/local && wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz && tar zxvf android-sdk_r24.4.1-linux.tgz && rm -rf /usr/local/android-sdk_r24.4.1-linux.tgz
      - export ANDROID_HOME="/usr/local/android-sdk-linux"
      - export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$PATH"
      - echo $ANDROID_HOME
      - cp android-sdk-license $ANDROID_HOME/licenses/
      - ./gradlew assemble
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - app/build/outputs/apt/app-release.apk