version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - sudo apt-get -y install wget
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - ./gradlew assemble
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - app/build/outputs/apk/app-debug.apk
